server:
  servlet:
    context-path: /trip_expenses

spring:
  datasource:
    url: 'jdbc:h2:mem:trip_expenses'
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true